import { bindPointLightEditorControls } from "./bindings/pointLightEditorBinding.js";

export function bindPointLightEditorRuntime(deps) {
  bindPointLightEditorControls({
    pointLightColorInput: deps.pointLightColorInput,
    pointLightStrengthInput: deps.pointLightStrengthInput,
    pointLightIntensityInput: deps.pointLightIntensityInput,
    pointLightHeightOffsetInput: deps.pointLightHeightOffsetInput,
    pointLightFlickerInput: deps.pointLightFlickerInput,
    pointLightFlickerSpeedInput: deps.pointLightFlickerSpeedInput,
    pointLightLiveUpdateToggle: deps.pointLightLiveUpdateToggle,
    lightSaveBtn: deps.lightSaveBtn,
    lightCancelBtn: deps.lightCancelBtn,
    lightDeleteBtn: deps.lightDeleteBtn,
    pointLightsSaveAllBtn: deps.pointLightsSaveAllBtn,
    pointLightsLoadAllBtn: deps.pointLightsLoadAllBtn,
    pointLightsLoadInput: deps.pointLightsLoadInput,
    clamp: deps.clamp,
    hexToRgb01: deps.hexToRgb01,
    hasLightEditDraft: deps.hasLightEditDraft,
    setLightEditDraftColor: deps.setLightEditDraftColor,
    setLightEditDraftStrength: deps.setLightEditDraftStrength,
    setLightEditDraftIntensity: deps.setLightEditDraftIntensity,
    setLightEditDraftHeightOffset: deps.setLightEditDraftHeightOffset,
    setLightEditDraftFlicker: deps.setLightEditDraftFlicker,
    setLightEditDraftFlickerSpeed: deps.setLightEditDraftFlickerSpeed,
    updatePointLightStrengthLabel: deps.updatePointLightStrengthLabel,
    updatePointLightIntensityLabel: deps.updatePointLightIntensityLabel,
    updatePointLightHeightOffsetLabel: deps.updatePointLightHeightOffsetLabel,
    updatePointLightFlickerLabel: deps.updatePointLightFlickerLabel,
    updatePointLightFlickerSpeedLabel: deps.updatePointLightFlickerSpeedLabel,
    rebakeIfPointLightLiveUpdateEnabled: deps.rebakeIfPointLightLiveUpdateEnabled,
    requestOverlayDraw: deps.requestOverlayDraw,
    applyDraftToSelectedPointLight: deps.applyDraftToSelectedPointLight,
    bakePointLightsTexture: deps.bakePointLightsTexture,
    dispatchCoreCommand: deps.dispatchCoreCommand,
    syncPointLightsStateToStore: deps.syncPointLightsStateToStore,
    updateLightEditorUi: deps.updateLightEditorUi,
    getSelectedPointLight: deps.getSelectedPointLight,
    deletePointLightById: deps.deletePointLightById,
    clearLightEditSelection: deps.clearLightEditSelection,
    isPointLightsSaveConfirmArmed: deps.isPointLightsSaveConfirmArmed,
    armPointLightsSaveConfirmation: deps.armPointLightsSaveConfirmation,
    resetPointLightsSaveConfirmation: deps.resetPointLightsSaveConfirmation,
    savePointLightsJson: deps.savePointLightsJson,
    loadPointLightsFromAssetsOrPrompt: deps.loadPointLightsFromAssetsOrPrompt,
    applyLoadedPointLights: deps.applyLoadedPointLights,
    setStatus: deps.setStatus,
  });
}
