import {
  updateShadowBlurLabel,
  updateSimTickLabel,
  updateFogAlphaLabels,
  updateFogFalloffLabel,
  updateFogStartOffsetLabel,
  updatePointFlickerLabels,
  updatePointFlickerUi,
  updateVolumetricLabels,
  updateVolumetricUi,
  updateCloudLabels,
  updateWaterLabels,
  updateFogUi,
  updateCloudUi,
  updateWaterUi,
} from "./renderFxUiRuntime.js";

export function createRenderFxUiBindingRuntime(deps) {
  return {
    updateShadowBlurLabel: () => updateShadowBlurLabel({
      clamp: deps.clamp,
      serializeLightingSettings: deps.serializeLightingSettings,
      shadowBlurValue: deps.shadowBlurValue,
    }),
    updateSimTickLabel: () => updateSimTickLabel({
      normalizeSimTickHours: deps.normalizeSimTickHours,
      serializeLightingSettings: deps.serializeLightingSettings,
      simTickHoursValue: deps.simTickHoursValue,
    }),
    updateFogAlphaLabels: () => updateFogAlphaLabels({
      clamp: deps.clamp,
      serializeFogSettings: deps.serializeFogSettings,
      fogMinAlphaValue: deps.fogMinAlphaValue,
      fogMaxAlphaValue: deps.fogMaxAlphaValue,
    }),
    updateFogFalloffLabel: () => updateFogFalloffLabel({
      clamp: deps.clamp,
      serializeFogSettings: deps.serializeFogSettings,
      fogFalloffValue: deps.fogFalloffValue,
    }),
    updateFogStartOffsetLabel: () => updateFogStartOffsetLabel({
      clamp: deps.clamp,
      serializeFogSettings: deps.serializeFogSettings,
      fogStartOffsetValue: deps.fogStartOffsetValue,
    }),
    updatePointFlickerLabels: () => updatePointFlickerLabels({
      clamp: deps.clamp,
      serializeLightingSettings: deps.serializeLightingSettings,
      pointFlickerStrengthValue: deps.pointFlickerStrengthValue,
      pointFlickerSpeedValue: deps.pointFlickerSpeedValue,
      pointFlickerSpatialValue: deps.pointFlickerSpatialValue,
    }),
    updatePointFlickerUi: () => updatePointFlickerUi({
      pointFlickerStrengthInput: deps.pointFlickerStrengthInput,
      pointFlickerSpeedInput: deps.pointFlickerSpeedInput,
      pointFlickerSpatialInput: deps.pointFlickerSpatialInput,
    }),
    updateVolumetricLabels: () => updateVolumetricLabels({
      clamp: deps.clamp,
      serializeLightingSettings: deps.serializeLightingSettings,
      volumetricStrengthValue: deps.volumetricStrengthValue,
      volumetricDensityValue: deps.volumetricDensityValue,
      volumetricAnisotropyValue: deps.volumetricAnisotropyValue,
      volumetricLengthValue: deps.volumetricLengthValue,
      volumetricSamplesValue: deps.volumetricSamplesValue,
    }),
    updateVolumetricUi: () => updateVolumetricUi({
      volumetricStrengthInput: deps.volumetricStrengthInput,
      volumetricDensityInput: deps.volumetricDensityInput,
      volumetricAnisotropyInput: deps.volumetricAnisotropyInput,
      volumetricLengthInput: deps.volumetricLengthInput,
      volumetricSamplesInput: deps.volumetricSamplesInput,
    }),
    updateCloudLabels: () => updateCloudLabels({
      clamp: deps.clamp,
      serializeCloudSettings: deps.serializeCloudSettings,
      cloudCoverageValue: deps.cloudCoverageValue,
      cloudSoftnessValue: deps.cloudSoftnessValue,
      cloudOpacityValue: deps.cloudOpacityValue,
      cloudScaleValue: deps.cloudScaleValue,
      cloudSpeed1Value: deps.cloudSpeed1Value,
      cloudSpeed2Value: deps.cloudSpeed2Value,
      cloudSunParallaxValue: deps.cloudSunParallaxValue,
    }),
    updateWaterLabels: () => updateWaterLabels({
      clamp: deps.clamp,
      serializeWaterSettings: deps.serializeWaterSettings,
      waterFlowDirectionValue: deps.waterFlowDirectionValue,
      waterLocalFlowMixValue: deps.waterLocalFlowMixValue,
      waterDownhillBoostValue: deps.waterDownhillBoostValue,
      waterFlowRadius1Value: deps.waterFlowRadius1Value,
      waterFlowRadius2Value: deps.waterFlowRadius2Value,
      waterFlowRadius3Value: deps.waterFlowRadius3Value,
      waterFlowWeight1Value: deps.waterFlowWeight1Value,
      waterFlowWeight2Value: deps.waterFlowWeight2Value,
      waterFlowWeight3Value: deps.waterFlowWeight3Value,
      waterFlowStrengthValue: deps.waterFlowStrengthValue,
      waterFlowMapStrengthValue: deps.waterFlowMapStrengthValue,
      waterFlowVisibilityValue: deps.waterFlowVisibilityValue,
      waterStreamlineDensityValue: deps.waterStreamlineDensityValue,
      waterStreamlineSharpnessValue: deps.waterStreamlineSharpnessValue,
      waterFlowSpeedValue: deps.waterFlowSpeedValue,
      waterFlowScaleValue: deps.waterFlowScaleValue,
      waterShimmerStrengthValue: deps.waterShimmerStrengthValue,
      waterGlintStrengthValue: deps.waterGlintStrengthValue,
      waterGlintSharpnessValue: deps.waterGlintSharpnessValue,
      waterShoreFoamStrengthValue: deps.waterShoreFoamStrengthValue,
      waterShoreWidthValue: deps.waterShoreWidthValue,
      waterReflectivityValue: deps.waterReflectivityValue,
      waterOpacityValue: deps.waterOpacityValue,
      waterTintStrengthValue: deps.waterTintStrengthValue,
    }),
    updateFogUi: () => updateFogUi({
      fogColorInput: deps.fogColorInput,
      fogMinAlphaInput: deps.fogMinAlphaInput,
      fogMaxAlphaInput: deps.fogMaxAlphaInput,
      fogFalloffInput: deps.fogFalloffInput,
      fogStartOffsetInput: deps.fogStartOffsetInput,
    }),
    updateCloudUi: () => updateCloudUi({
      cloudCoverageInput: deps.cloudCoverageInput,
      cloudSoftnessInput: deps.cloudSoftnessInput,
      cloudOpacityInput: deps.cloudOpacityInput,
      cloudScaleInput: deps.cloudScaleInput,
      cloudSpeed1Input: deps.cloudSpeed1Input,
      cloudSpeed2Input: deps.cloudSpeed2Input,
      cloudSunParallaxInput: deps.cloudSunParallaxInput,
      cloudSunProjectToggle: deps.cloudSunProjectToggle,
    }),
    updateWaterUi: () => updateWaterUi({
      serializeWaterSettings: deps.serializeWaterSettings,
      waterFlowSourceInput: deps.waterFlowSourceInput,
      waterFlowRenderModeInput: deps.waterFlowRenderModeInput,
      waterFlowChannelPairInput: deps.waterFlowChannelPairInput,
      waterFlowFlipXToggle: deps.waterFlowFlipXToggle,
      waterFlowFlipYToggle: deps.waterFlowFlipYToggle,
      waterFlowUseMagnitudeToggle: deps.waterFlowUseMagnitudeToggle,
      waterFlowInvertDownhillToggle: deps.waterFlowInvertDownhillToggle,
      waterFlowDebugToggle: deps.waterFlowDebugToggle,
      waterFlowDirectionInput: deps.waterFlowDirectionInput,
      waterLocalFlowMixInput: deps.waterLocalFlowMixInput,
      waterDownhillBoostInput: deps.waterDownhillBoostInput,
      waterFlowRadius1Input: deps.waterFlowRadius1Input,
      waterFlowRadius2Input: deps.waterFlowRadius2Input,
      waterFlowRadius3Input: deps.waterFlowRadius3Input,
      waterFlowWeight1Input: deps.waterFlowWeight1Input,
      waterFlowWeight2Input: deps.waterFlowWeight2Input,
      waterFlowWeight3Input: deps.waterFlowWeight3Input,
      waterFlowStrengthInput: deps.waterFlowStrengthInput,
      waterFlowMapStrengthInput: deps.waterFlowMapStrengthInput,
      waterFlowVisibilityInput: deps.waterFlowVisibilityInput,
      waterStreamlineDensityInput: deps.waterStreamlineDensityInput,
      waterStreamlineSharpnessInput: deps.waterStreamlineSharpnessInput,
      waterFlowSpeedInput: deps.waterFlowSpeedInput,
      waterFlowScaleInput: deps.waterFlowScaleInput,
      waterShimmerStrengthInput: deps.waterShimmerStrengthInput,
      waterGlintStrengthInput: deps.waterGlintStrengthInput,
      waterGlintSharpnessInput: deps.waterGlintSharpnessInput,
      waterShoreFoamStrengthInput: deps.waterShoreFoamStrengthInput,
      waterShoreWidthInput: deps.waterShoreWidthInput,
      waterReflectivityInput: deps.waterReflectivityInput,
      waterBaseColorInput: deps.waterBaseColorInput,
      waterOpacityInput: deps.waterOpacityInput,
      waterTintColorInput: deps.waterTintColorInput,
      waterTintStrengthInput: deps.waterTintStrengthInput,
    }),
  };
}
