import { bindSwarmPanelControls } from "./bindings/swarmPanelBinding.js";

export function bindSwarmPanelRuntime(deps) {
  bindSwarmPanelControls({
    swarmShowTerrainToggle: deps.swarmShowTerrainToggle,
    swarmLitModeToggle: deps.swarmLitModeToggle,
    swarmFollowZoomToggle: deps.swarmFollowZoomToggle,
    swarmFollowZoomInInput: deps.swarmFollowZoomInInput,
    swarmFollowZoomOutInput: deps.swarmFollowZoomOutInput,
    swarmFollowHawkRangeGizmoToggle: deps.swarmFollowHawkRangeGizmoToggle,
    swarmFollowAgentSpeedSmoothingInput: deps.swarmFollowAgentSpeedSmoothingInput,
    swarmFollowAgentZoomSmoothingInput: deps.swarmFollowAgentZoomSmoothingInput,
    swarmStatsPanelToggle: deps.swarmStatsPanelToggle,
    swarmBackgroundColorInput: deps.swarmBackgroundColorInput,
    swarmAgentCountInput: deps.swarmAgentCountInput,
    swarmUpdateIntervalInput: deps.swarmUpdateIntervalInput,
    swarmMaxSpeedInput: deps.swarmMaxSpeedInput,
    swarmSteeringMaxInput: deps.swarmSteeringMaxInput,
    swarmVariationStrengthInput: deps.swarmVariationStrengthInput,
    swarmNeighborRadiusInput: deps.swarmNeighborRadiusInput,
    swarmMinHeightInput: deps.swarmMinHeightInput,
    swarmMaxHeightInput: deps.swarmMaxHeightInput,
    swarmSeparationRadiusInput: deps.swarmSeparationRadiusInput,
    swarmAlignmentWeightInput: deps.swarmAlignmentWeightInput,
    swarmCohesionWeightInput: deps.swarmCohesionWeightInput,
    swarmSeparationWeightInput: deps.swarmSeparationWeightInput,
    swarmWanderWeightInput: deps.swarmWanderWeightInput,
    swarmRestChanceInput: deps.swarmRestChanceInput,
    swarmRestTicksInput: deps.swarmRestTicksInput,
    swarmBreedingThresholdInput: deps.swarmBreedingThresholdInput,
    swarmBreedingSpawnChanceInput: deps.swarmBreedingSpawnChanceInput,
    swarmCursorModeInput: deps.swarmCursorModeInput,
    swarmCursorStrengthInput: deps.swarmCursorStrengthInput,
    swarmCursorRadiusInput: deps.swarmCursorRadiusInput,
    swarmHawkEnabledToggle: deps.swarmHawkEnabledToggle,
    swarmHawkCountInput: deps.swarmHawkCountInput,
    swarmHawkColorInput: deps.swarmHawkColorInput,
    swarmHawkSpeedInput: deps.swarmHawkSpeedInput,
    swarmHawkSteeringInput: deps.swarmHawkSteeringInput,
    swarmHawkTargetRangeInput: deps.swarmHawkTargetRangeInput,
    swarmTimeRoutingInput: deps.swarmTimeRoutingInput,
    swarmEnabledToggle: deps.swarmEnabledToggle,
    dispatchCoreCommand: deps.dispatchCoreCommand,
    swarmState: deps.swarmState,
    swarmCursorState: deps.swarmCursorState,
    swarmFollowState: deps.swarmFollowState,
    clamp: deps.clamp,
    getSwarmSettings: deps.getSwarmSettings,
    updateSwarmUi: deps.updateSwarmUi,
    updateSwarmLabels: deps.updateSwarmLabels,
    updateSwarmStatsPanel: deps.updateSwarmStatsPanel,
    normalizeSwarmFollowZoomInputs: deps.normalizeSwarmFollowZoomInputs,
    normalizeSwarmHeightRangeInputs: deps.normalizeSwarmHeightRangeInputs,
    reseedSwarmAgents: deps.reseedSwarmAgents,
    resetSwarmFollowSpeedSmoothing: deps.resetSwarmFollowSpeedSmoothing,
    updateSwarmFollowButtonUi: deps.updateSwarmFollowButtonUi,
    requestOverlayDraw: deps.requestOverlayDraw,
    setStatus: deps.setStatus,
  });
}
