export function createUiRuntimeFacade(deps) {
  return {
    updateLightEditorUi: () => deps.getLightInteractionRuntimeBinding().updateLightEditorUi(),
    beginLightEdit: (light) => deps.getLightInteractionRuntimeBinding().beginLightEdit(light),
    applyDraftToSelectedPointLight: () => deps.getLightInteractionRuntimeBinding().applyDraftToSelectedPointLight(),
    rebakeIfPointLightLiveUpdateEnabled: () => deps.getLightInteractionRuntimeBinding().rebakeIfPointLightLiveUpdateEnabled(),
    findPointLightAtPixel: (pixelX, pixelY, radiusPx) =>
      deps.getLightInteractionRuntimeBinding().findPointLightAtPixel(pixelX, pixelY, radiusPx),
    createPointLight: (pixelX, pixelY) => deps.getLightInteractionRuntimeBinding().createPointLight(pixelX, pixelY),
    getGrayAt: (imageData, x, y, sourceWidth, sourceHeight) =>
      deps.getPathfindingRuntimeBinding().getGrayAt(imageData, x, y, sourceWidth, sourceHeight),
    computeMoveStepCost: (fromX, fromY, toX, toY) =>
      deps.getPathfindingRuntimeBinding().computeMoveStepCost(fromX, fromY, toX, toY),
    rebuildMovementField: () => deps.getPathfindingRuntimeBinding().rebuildMovementField(),
    extractPathTo: (pixelX, pixelY) => deps.getPathfindingRuntimeBinding().extractPathTo(pixelX, pixelY),
    refreshPathPreview: () => deps.getPathfindingRuntimeBinding().refreshPathPreview(),
    updatePathPreviewFromPointer: (clientX, clientY) =>
      deps.getPathfindingRuntimeBinding().updatePathPreviewFromPointer(clientX, clientY),
    getCurrentPathMetrics: () => deps.getPathfindingRuntimeBinding().getCurrentPathMetrics(),
    updatePathfindingRangeLabel: () => deps.getPathfindingLabelBindingRuntime().updatePathfindingRangeLabel(),
    updatePathWeightLabels: () => deps.getPathfindingLabelBindingRuntime().updatePathWeightLabels(),
    updatePathSlopeCutoffLabel: () => deps.getPathfindingLabelBindingRuntime().updatePathSlopeCutoffLabel(),
    updatePathBaseCostLabel: () => deps.getPathfindingLabelBindingRuntime().updatePathBaseCostLabel(),
    updateParallaxStrengthLabel: () => deps.getRenderFxUiBindingRuntime().updateParallaxStrengthLabel(),
    updateParallaxBandsLabel: () => deps.getRenderFxUiBindingRuntime().updateParallaxBandsLabel(),
    updateShadowBlurLabel: () => deps.getRenderFxUiBindingRuntime().updateShadowBlurLabel(),
    updateSimTickLabel: () => deps.getRenderFxUiBindingRuntime().updateSimTickLabel(),
    updateFogAlphaLabels: () => deps.getRenderFxUiBindingRuntime().updateFogAlphaLabels(),
    updateFogFalloffLabel: () => deps.getRenderFxUiBindingRuntime().updateFogFalloffLabel(),
    updateFogStartOffsetLabel: () => deps.getRenderFxUiBindingRuntime().updateFogStartOffsetLabel(),
    updatePointFlickerLabels: () => deps.getRenderFxUiBindingRuntime().updatePointFlickerLabels(),
    updatePointFlickerUi: () => deps.getRenderFxUiBindingRuntime().updatePointFlickerUi(),
    updateVolumetricLabels: () => deps.getRenderFxUiBindingRuntime().updateVolumetricLabels(),
    updateVolumetricUi: () => deps.getRenderFxUiBindingRuntime().updateVolumetricUi(),
    updateCloudLabels: () => deps.getRenderFxUiBindingRuntime().updateCloudLabels(),
    updateWaterLabels: () => deps.getRenderFxUiBindingRuntime().updateWaterLabels(),
    updateParallaxUi: () => deps.getRenderFxUiBindingRuntime().updateParallaxUi(),
    updateFogUi: () => deps.getRenderFxUiBindingRuntime().updateFogUi(),
    updateCloudUi: () => deps.getRenderFxUiBindingRuntime().updateCloudUi(),
    updateWaterUi: () => deps.getRenderFxUiBindingRuntime().updateWaterUi(),
    syncRenderFxParallaxUi: () => deps.getRenderFxSettingsSyncRuntime().syncParallaxUi(),
    syncRenderFxLightingUi: () => deps.getRenderFxSettingsSyncRuntime().syncLightingUi(),
    syncRenderFxFogUi: () => deps.getRenderFxSettingsSyncRuntime().syncFogUi(),
    syncRenderFxCloudUi: () => deps.getRenderFxSettingsSyncRuntime().syncCloudUi(),
    syncRenderFxWaterUi: () => deps.getRenderFxSettingsSyncRuntime().syncWaterUi(),
    updatePointLightStrengthLabel: (value = null) => deps.getLightLabelBindingRuntime().updatePointLightStrengthLabel(value),
    updatePointLightIntensityLabel: (value = null) => deps.getLightLabelBindingRuntime().updatePointLightIntensityLabel(value),
    updatePointLightHeightOffsetLabel: (value = null) => deps.getLightLabelBindingRuntime().updatePointLightHeightOffsetLabel(value),
    updatePointLightFlickerLabel: (value = null) => deps.getLightLabelBindingRuntime().updatePointLightFlickerLabel(value),
    updatePointLightFlickerSpeedLabel: (value = null) => deps.getLightLabelBindingRuntime().updatePointLightFlickerSpeedLabel(value),
    updateCursorLightStrengthLabel: () => deps.getLightLabelBindingRuntime().updateCursorLightStrengthLabel(),
    updateCursorLightHeightOffsetLabel: () => deps.getLightLabelBindingRuntime().updateCursorLightHeightOffsetLabel(),
  };
}
